"""Run-scoped credential broker for isolated Kimi Code benchmark stages.

The parent-side :class:`RunScopedProviderBroker` never accepts a credential as
text.  It starts exactly one child process for one ``run_id/case_id/trial_id``
and passes an already-open credential descriptor to that child.  The worker
reads and closes the descriptor before accepting clients.  Credentials are
never placed in argv, the environment, an attestation, or an evidence file.

Kimi reaches the worker through the private AF_UNIX socket protocol consumed by
``sandbox_entry.py``.  A nonce is generated by the worker and returned to the
launcher as a sealed memfd over a private control socket.  Each nonce permits
one authenticated broker connection; that connection may carry sequential
HTTP/1.1 requests.  A second connection with the same nonce is a replay and is
rejected.

Only two upstream shapes are accepted:

* loopback IP-literal HTTP, intended for credential-free local validation; or
* HTTPS to one exact, constructor-reviewed DNS host.

The worker injects ``Authorization: Bearer ...`` after removing every client
authorization/proxy header.  It does not implement a general forward proxy.
"""

from __future__ import annotations

from array import array
import argparse
import base64
from dataclasses import dataclass
from datetime import datetime, timezone
import fcntl
import hashlib
import hmac
import http.client
import ipaddress
import json
import os
from pathlib import Path
import re
import secrets
import signal
import socket
import ssl
import stat
import subprocess
import sys
import tempfile
import threading
from typing import Any, Mapping, Sequence
from urllib.parse import urlsplit


BROKER_ATTESTATION_SCHEMA_NAME = "safety_bench_kimi_external_broker_attestation"
BROKER_ATTESTATION_SCHEMA_VERSION = 1
AUDIT_ATTESTATION_SCHEMA_NAME = "safety_bench_kimi_provider_broker_audit"
AUDIT_ATTESTATION_SCHEMA_VERSION = 1
HANDSHAKE_SCHEMA_NAME = "safety_bench_kimi_relay_handshake"
REQUEST_OBSERVATION_SCHEMA_NAME = (
    "safety_bench_kimi_provider_request_observation"
)
REQUEST_OBSERVATION_SCHEMA_VERSION = 1
BROKER_ROOT_PREFIX = "p"
BROKER_SOCKET_BASENAME = "p.sock"
LINUX_AF_UNIX_PATH_LIMIT = 108
SERVICE_IDENTITY_DIGEST_HEX_LENGTH = 16

_SAFE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,159}$")
_RUN_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$")
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_DNS_NAME_RE = re.compile(
    r"^(?=.{1,253}\.?$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*"
    r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$"
)
_SENSITIVE_ENV_RE = re.compile(
    r"(?:api[_-]?key|token|secret|password|credential|bearer|auth)", re.IGNORECASE
)
_MAX_CONTROL_PACKET = 64 * 1024
_MAX_HANDSHAKE_LINE = 64 * 1024
_MAX_HTTP_LINE = 64 * 1024
_MAX_HTTP_HEADERS = 256
_MAX_REQUEST_BODY = 64 * 1024 * 1024
_MAX_INSTRUCTION_MARKER = 8 * 1024
_HOP_BY_HOP_HEADERS = {
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
}
_CLIENT_RELAY_PATH_PREFIX = "/v1"


class KimiProviderBrokerError(RuntimeError):
    """The provider broker could not preserve its credential boundary."""


def _require_id(value: str, label: str) -> str:
    if not isinstance(value, str) or _SAFE_ID_RE.fullmatch(value) is None:
        raise KimiProviderBrokerError(
            f"{label} must be 1-160 safe ASCII characters"
        )
    return value


def _require_run_id(value: str) -> str:
    if not isinstance(value, str) or _RUN_ID_RE.fullmatch(value) is None:
        raise KimiProviderBrokerError(
            "run_id must be 1-80 safe ASCII characters"
        )
    return value


def broker_identity_digest(run_id: str, case_id: str, trial_id: str) -> str:
    """Return the collision-resistant short identity used by the socket root."""

    checked_run = _require_run_id(run_id)
    checked_case = _require_id(case_id, "case_id")
    checked_trial = _require_id(trial_id, "trial_id")
    return hashlib.sha256(
        f"{checked_run}\0{checked_case}\0{checked_trial}".encode("utf-8")
    ).hexdigest()[:SERVICE_IDENTITY_DIGEST_HEX_LENGTH]


def broker_root_name(run_id: str, case_id: str, trial_id: str) -> str:
    return f"{BROKER_ROOT_PREFIX}-{broker_identity_digest(run_id, case_id, trial_id)}"


def _canonical_sha256(document: Mapping[str, Any]) -> str:
    return hashlib.sha256(
        json.dumps(
            document,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        ).encode("utf-8")
    ).hexdigest()


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _process_start_time(pid: int) -> str:
    try:
        raw = Path(f"/proc/{pid}/stat").read_text(encoding="utf-8")
    except OSError as exc:
        raise KimiProviderBrokerError("broker process is not observable") from exc
    closing = raw.rfind(")")
    fields = raw[closing + 1 :].split() if closing >= 0 else []
    if len(fields) < 20:
        raise KimiProviderBrokerError("broker process stat is malformed")
    return fields[19]


def _process_cmdline_sha256(pid: int) -> str:
    try:
        value = Path(f"/proc/{pid}/cmdline").read_bytes()
    except OSError as exc:
        raise KimiProviderBrokerError("broker cmdline is not observable") from exc
    if not value:
        raise KimiProviderBrokerError("broker cmdline is empty")
    return hashlib.sha256(value).hexdigest()


def _ack_proof(
    nonce: bytes | bytearray,
    *,
    run_id: str,
    stage_index: int,
    purpose: str,
    ok: bool,
) -> str:
    message = "\0".join(
        (
            HANDSHAKE_SCHEMA_NAME,
            run_id,
            str(stage_index),
            purpose,
            "ok" if ok else "rejected",
        )
    ).encode("utf-8")
    return hmac.new(bytes(nonce), message, hashlib.sha256).hexdigest()


def _wipe(value: bytearray) -> None:
    for index in range(len(value)):
        value[index] = 0


def _is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def _reject_symlink_chain(path: Path, *, stop: Path, label: str) -> None:
    candidate = path.absolute()
    boundary = stop.absolute()
    while True:
        if candidate.is_symlink():
            raise KimiProviderBrokerError(f"{label} has a symlink component")
        if candidate == boundary:
            return
        if candidate.parent == candidate or not _is_relative_to(candidate, boundary):
            raise KimiProviderBrokerError(f"{label} escapes ownership_root")
        candidate = candidate.parent


def _atomic_json(path: Path, document: Mapping[str, Any]) -> None:
    if path.exists() or path.is_symlink():
        raise KimiProviderBrokerError(f"refusing to replace broker evidence: {path}")
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix="tmp-kimi-provider-broker-"
    )
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            json.dump(document, handle, indent=2, sort_keys=True, ensure_ascii=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


@dataclass(frozen=True)
class UpstreamEndpoint:
    """A validated, non-proxy upstream destination."""

    scheme: str
    host: str
    port: int
    path_prefix: str
    tls_verified: bool

    @classmethod
    def parse(
        cls,
        value: str,
        *,
        allowed_https_hosts: Sequence[str] = (),
    ) -> "UpstreamEndpoint":
        if not isinstance(value, str) or not value or "\0" in value:
            raise KimiProviderBrokerError("upstream URL must be a non-empty string")
        parsed = urlsplit(value)
        if (
            parsed.scheme not in {"http", "https"}
            or parsed.hostname is None
            or parsed.username is not None
            or parsed.password is not None
            or parsed.query
            or parsed.fragment
        ):
            raise KimiProviderBrokerError("upstream URL shape is not allowed")
        try:
            port = parsed.port or (443 if parsed.scheme == "https" else 80)
        except ValueError as exc:
            raise KimiProviderBrokerError("upstream port is malformed") from exc
        if not 1 <= port <= 65535:
            raise KimiProviderBrokerError("upstream port is out of range")
        path_prefix = parsed.path.rstrip("/") or "/"
        if not path_prefix.startswith("/") or ".." in path_prefix.split("/"):
            raise KimiProviderBrokerError("upstream path prefix is unsafe")
        raw_host = parsed.hostname.rstrip(".").casefold()
        if parsed.scheme == "http":
            try:
                address = ipaddress.ip_address(raw_host)
            except ValueError as exc:
                raise KimiProviderBrokerError(
                    "plain HTTP upstream must use a loopback IP literal"
                ) from exc
            if not address.is_loopback:
                raise KimiProviderBrokerError(
                    "plain HTTP upstream must use a loopback IP literal"
                )
            host = address.compressed
            tls_verified = False
        else:
            try:
                ipaddress.ip_address(raw_host)
            except ValueError:
                pass
            else:
                raise KimiProviderBrokerError(
                    "production HTTPS upstream must use an allowlisted DNS host"
                )
            try:
                host = raw_host.encode("idna").decode("ascii")
            except UnicodeError as exc:
                raise KimiProviderBrokerError("HTTPS upstream host is invalid") from exc
            if _DNS_NAME_RE.fullmatch(host) is None:
                raise KimiProviderBrokerError("HTTPS upstream host is invalid")
            normalized_allowlist = {
                item.rstrip(".").casefold().encode("idna").decode("ascii")
                for item in allowed_https_hosts
                if isinstance(item, str) and item
            }
            if host not in normalized_allowlist:
                raise KimiProviderBrokerError(
                    "HTTPS upstream host lacks an exact constructor allowlist entry"
                )
            tls_verified = True
        return cls(
            scheme=parsed.scheme,
            host=host,
            port=port,
            path_prefix=path_prefix,
            tls_verified=tls_verified,
        )

    @property
    def authority(self) -> str:
        default = 443 if self.scheme == "https" else 80
        host = f"[{self.host}]" if ":" in self.host else self.host
        return host if self.port == default else f"{host}:{self.port}"


@dataclass(frozen=True)
class BrokerNonceFD:
    """Opaque launcher lease containing a sealed 32-byte nonce."""

    fd: int
    lease_id: str


@dataclass(frozen=True)
class InstructionRequestObservation:
    """Immutable locator for one directly observed provider request.

    The model request body is deliberately absent.  Only its digest, the
    ordered message roles, and the configured instruction-marker digest leave
    the broker process.
    """

    path: Path
    sha256: str
    line: int
    line_count: int
    body_sha256: str
    marker_sha256: str
    message_roles: tuple[str, ...]
    observed_time: str

    def as_reference(self) -> dict[str, Any]:
        return {
            "path": str(self.path),
            "sha256": self.sha256,
            "line": self.line,
        }


@dataclass
class _Lease:
    run_id: str
    stage_index: int
    purpose: str
    nonce: bytearray
    consumed: bool = False


@dataclass
class _InstructionObserver:
    stage_index: int
    path: Path
    marker: bytearray
    marker_sha256: str
    expected_roles: tuple[str, ...]
    sequence: int = 0
    finalized: bool = False


def _credential_descriptor_shape(descriptor: int) -> str:
    if not isinstance(descriptor, int) or isinstance(descriptor, bool) or descriptor < 3:
        raise KimiProviderBrokerError("credential_fd must be an open descriptor >= 3")
    try:
        metadata = os.fstat(descriptor)
        flags = fcntl.fcntl(descriptor, fcntl.F_GETFD)
    except OSError as exc:
        raise KimiProviderBrokerError("credential_fd is unavailable") from exc
    if flags & fcntl.FD_CLOEXEC == 0:
        raise KimiProviderBrokerError("credential_fd must be close-on-exec by default")
    if stat.S_ISFIFO(metadata.st_mode):
        return "pipe_fd"
    if stat.S_ISREG(metadata.st_mode):
        try:
            target = os.readlink(f"/proc/self/fd/{descriptor}")
            seals = fcntl.fcntl(descriptor, fcntl.F_GET_SEALS)
        except OSError as exc:
            raise KimiProviderBrokerError(
                "regular credential_fd must be an observable sealed memfd"
            ) from exc
        required = (
            fcntl.F_SEAL_SEAL
            | fcntl.F_SEAL_SHRINK
            | fcntl.F_SEAL_GROW
            | fcntl.F_SEAL_WRITE
        )
        if "memfd:" not in target or seals & required != required:
            raise KimiProviderBrokerError(
                "regular credential_fd must be a sealed memfd"
            )
        return "sealed_memfd"
    raise KimiProviderBrokerError("credential_fd must be a pipe or sealed memfd")


def _recv_packet(connection: socket.socket) -> tuple[Mapping[str, Any], list[int]]:
    flags = getattr(socket, "MSG_CMSG_CLOEXEC", 0)
    payload, ancillary, message_flags, _ = connection.recvmsg(
        _MAX_CONTROL_PACKET,
        socket.CMSG_SPACE(array("i", [0]).itemsize),
        flags,
    )
    if not payload or message_flags & (socket.MSG_TRUNC | socket.MSG_CTRUNC):
        raise KimiProviderBrokerError("broker control packet is absent or truncated")
    try:
        document = json.loads(payload.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise KimiProviderBrokerError("broker control packet is malformed") from exc
    if not isinstance(document, Mapping):
        raise KimiProviderBrokerError("broker control packet must be an object")
    descriptors: list[int] = []
    for level, kind, data in ancillary:
        if level == socket.SOL_SOCKET and kind == socket.SCM_RIGHTS:
            values = array("i")
            values.frombytes(data[: len(data) - (len(data) % values.itemsize)])
            descriptors.extend(values)
    return document, descriptors


def _send_packet(
    connection: socket.socket,
    document: Mapping[str, Any],
    *,
    descriptor: int | None = None,
) -> None:
    payload = json.dumps(
        document, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")
    ancillary: list[tuple[int, int, bytes]] = []
    if descriptor is not None:
        ancillary.append((socket.SOL_SOCKET, socket.SCM_RIGHTS, array("i", [descriptor])))
    sent = connection.sendmsg([payload], ancillary)
    if sent != len(payload):
        raise KimiProviderBrokerError("broker control packet was partially sent")


class RunScopedProviderBroker:
    """Parent-side handle for one independently owned broker subprocess."""

    def __init__(
        self,
        *,
        ownership_root: Path | str,
        run_id: str,
        case_id: str,
        trial_id: str,
        upstream_url: str,
        credential_fd: int,
        allowed_https_hosts: Sequence[str] = (),
        python_executable: Path | str | None = None,
        startup_timeout: float = 15.0,
        upstream_timeout: float = 300.0,
    ) -> None:
        self.run_id = _require_run_id(run_id)
        self.case_id = _require_id(case_id, "case_id")
        self.trial_id = _require_id(trial_id, "trial_id")
        self.endpoint = UpstreamEndpoint.parse(
            upstream_url, allowed_https_hosts=allowed_https_hosts
        )
        self.credential_transport = _credential_descriptor_shape(credential_fd)
        ownership = Path(ownership_root).absolute()
        if not ownership.is_dir() or ownership.is_symlink():
            raise KimiProviderBrokerError("ownership_root must be an existing directory")
        self.ownership_root = ownership.resolve(strict=True)
        if self.ownership_root != ownership or self.ownership_root.stat().st_mode & 0o077:
            raise KimiProviderBrokerError("ownership_root must be private and symlink-free")
        if (
            "kimi" not in self.ownership_root.as_posix().casefold()
            or self.run_id not in self.ownership_root.as_posix()
            or any(
                part.casefold() in {".claude", ".codex", ".kimi-code"}
                for part in self.ownership_root.parts
            )
        ):
            raise KimiProviderBrokerError("ownership_root lacks Kimi/run ownership")
        broker_name = broker_root_name(self.run_id, self.case_id, self.trial_id)
        self.root = self.ownership_root / broker_name
        _reject_symlink_chain(self.root, stop=self.ownership_root, label="broker root")
        if self.root.exists() or self.root.is_symlink():
            raise KimiProviderBrokerError("broker root already exists")
        self.socket_path = self.root / BROKER_SOCKET_BASENAME
        # Linux pathname AF_UNIX addresses have a 108-byte sockaddr field
        # including the terminating NUL.  Formal runs must therefore choose a
        # deliberately short external result root; silently relocating this
        # socket would break run ownership.
        socket_path_length = len(os.fsencode(self.socket_path))
        if socket_path_length >= LINUX_AF_UNIX_PATH_LIMIT:
            raise KimiProviderBrokerError(
                f"run-owned broker socket path is {socket_path_length} bytes and "
                "exceeds the Linux AF_UNIX pathname limit (107 bytes); choose "
                "a shorter --result-root or --run-id"
            )
        self.root.mkdir(mode=0o700)
        self.attestation_path = self.root / f"attestation-kimi-{self.run_id}.json"
        self.audit_attestation_path = (
            self.root / f"audit-attestation-kimi-{self.run_id}.json"
        )
        self.audit_log_path = self.root / f"audit-kimi-{self.run_id}.jsonl"
        executable = Path(
            python_executable or getattr(sys, "_base_executable", sys.executable)
        ).resolve(strict=True)
        implementation = Path(__file__).resolve(strict=True)
        if not executable.is_file() or not os.access(executable, os.X_OK):
            raise KimiProviderBrokerError("broker Python executable is unavailable")
        self.process_executable_path = executable
        self.process_executable_sha256 = _file_sha256(executable)
        self.implementation_path = implementation
        self.implementation_sha256 = _file_sha256(implementation)
        parent_control, child_control = socket.socketpair(
            socket.AF_UNIX, socket.SOCK_SEQPACKET | socket.SOCK_CLOEXEC
        )
        parent_control.settimeout(startup_timeout)
        command = [
            str(executable),
            str(implementation),
            "--worker",
            "--control-fd",
            str(child_control.fileno()),
            "--credential-fd",
            str(credential_fd),
            "--credential-transport",
            self.credential_transport,
            "--root",
            str(self.root),
            "--run-id",
            self.run_id,
            "--case-id",
            self.case_id,
            "--trial-id",
            self.trial_id,
            "--upstream-scheme",
            self.endpoint.scheme,
            "--upstream-host",
            self.endpoint.host,
            "--upstream-port",
            str(self.endpoint.port),
            "--upstream-path-prefix",
            self.endpoint.path_prefix,
            "--upstream-timeout",
            str(float(upstream_timeout)),
        ]
        environment = {
            "PATH": "/usr/local/bin:/usr/bin:/bin",
            "LANG": "C.UTF-8",
            "LC_ALL": "C.UTF-8",
            "PYTHONDONTWRITEBYTECODE": "1",
            "PYTHONNOUSERSITE": "1",
            "PYTHONSAFEPATH": "1",
        }
        self._control = parent_control
        self._rpc_lock = threading.Lock()
        self._closed = False
        self._instruction_observers: dict[
            int, tuple[Path, str, tuple[str, ...]]
        ] = {}
        self._process: subprocess.Popen[bytes] | None = None
        try:
            self._process = subprocess.Popen(
                command,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                cwd=self.root,
                env=environment,
                close_fds=True,
                pass_fds=(child_control.fileno(), credential_fd),
                start_new_session=True,
            )
            self.pid = self._process.pid
            self.start_time = _process_start_time(self.pid)
            child_control.close()
            try:
                ready, descriptors = _recv_packet(self._control)
            except KimiProviderBrokerError as exc:
                detail = ""
                try:
                    self._process.wait(timeout=1)
                except subprocess.TimeoutExpired:
                    pass
                if self._process.poll() is not None and self._process.stderr is not None:
                    detail = self._process.stderr.read(4096).decode(
                        "utf-8", errors="replace"
                    ).strip()
                raise KimiProviderBrokerError(
                    "broker worker exited before readiness "
                    f"(returncode={self._process.poll()}): {detail or 'no diagnostic'}"
                ) from exc
            for descriptor in descriptors:
                os.close(descriptor)
            if (
                set(ready) != {"ok", "operation", "pid"}
                or ready.get("ok") is not True
                or ready.get("operation") != "ready"
                or ready.get("pid") != self.pid
            ):
                raise KimiProviderBrokerError("broker worker did not attest readiness")
            self._control.settimeout(10.0)
            self._validate_live_identity()
            self._validate_evidence_files()
        except BaseException:
            child_control.close()
            self._stop_owned_process()
            self._control.close()
            self._closed = True
            raise

    def _validate_live_identity(self) -> None:
        if self._process is None or self._process.poll() is not None:
            raise KimiProviderBrokerError("broker worker is not running")
        if _process_start_time(self.pid) != self.start_time:
            raise KimiProviderBrokerError("broker PID identity drifted")
        try:
            executable = Path(f"/proc/{self.pid}/exe").resolve(strict=True)
        except OSError as exc:
            raise KimiProviderBrokerError("broker executable is not observable") from exc
        if (
            executable != self.process_executable_path
            or not hmac.compare_digest(
                _file_sha256(executable), self.process_executable_sha256
            )
        ):
            raise KimiProviderBrokerError("broker executable identity drifted")

    def _validate_evidence_files(self) -> None:
        for path in (
            self.attestation_path,
            self.audit_attestation_path,
            self.audit_log_path,
        ):
            if not path.is_file() or path.is_symlink() or stat.S_IMODE(path.stat().st_mode) != 0o600:
                raise KimiProviderBrokerError("broker evidence is absent or not private")
        if (
            not self.socket_path.exists()
            or self.socket_path.is_symlink()
            or not stat.S_ISSOCK(self.socket_path.stat().st_mode)
            or stat.S_IMODE(self.socket_path.stat().st_mode) != 0o600
        ):
            raise KimiProviderBrokerError("broker socket is absent or not private")
        audit = json.loads(self.audit_attestation_path.read_text(encoding="utf-8"))
        if (
            audit.get("run_id") != self.run_id
            or audit.get("case_id") != self.case_id
            or audit.get("trial_id") != self.trial_id
            or audit.get("pid") != self.pid
        ):
            raise KimiProviderBrokerError("broker audit identity drifted")

    def _rpc(
        self, document: Mapping[str, Any], *, expect_descriptor: bool = False
    ) -> tuple[Mapping[str, Any], int | None]:
        with self._rpc_lock:
            if self._closed:
                raise KimiProviderBrokerError("broker is closed")
            self._validate_live_identity()
            _send_packet(self._control, document)
            response, descriptors = _recv_packet(self._control)
        if response.get("ok") is not True:
            for descriptor in descriptors:
                os.close(descriptor)
            raise KimiProviderBrokerError(
                f"broker rejected {document.get('operation')}: {response.get('reason')}"
            )
        if expect_descriptor:
            if len(descriptors) != 1:
                for descriptor in descriptors:
                    os.close(descriptor)
                raise KimiProviderBrokerError("broker returned an invalid descriptor set")
            return response, descriptors[0]
        if descriptors:
            for descriptor in descriptors:
                os.close(descriptor)
            raise KimiProviderBrokerError("broker returned an unexpected descriptor")
        return response, None

    def issue_nonce_fd(
        self, *, run_id: str, stage_index: int, purpose: str
    ) -> BrokerNonceFD:
        if run_id != self.run_id:
            raise KimiProviderBrokerError("cross-run nonce issuance rejected")
        if (
            not isinstance(stage_index, int)
            or isinstance(stage_index, bool)
            or stage_index < -1
            or not isinstance(purpose, str)
            or _SAFE_ID_RE.fullmatch(purpose) is None
        ):
            raise KimiProviderBrokerError("nonce lease identity is malformed")
        response, descriptor = self._rpc(
            {
                "operation": "issue_nonce",
                "run_id": run_id,
                "case_id": self.case_id,
                "trial_id": self.trial_id,
                "stage_index": stage_index,
                "purpose": purpose,
            },
            expect_descriptor=True,
        )
        assert descriptor is not None
        lease_id = response.get("lease_id")
        try:
            if (
                not isinstance(lease_id, str)
                or _SAFE_ID_RE.fullmatch(lease_id) is None
                or "kimi" not in lease_id.casefold()
                or self.run_id not in lease_id
            ):
                raise KimiProviderBrokerError("broker returned an invalid lease identity")
            metadata = os.fstat(descriptor)
            seals = fcntl.fcntl(descriptor, fcntl.F_GET_SEALS)
            flags = fcntl.fcntl(descriptor, fcntl.F_GETFD)
            required = (
                fcntl.F_SEAL_SEAL
                | fcntl.F_SEAL_SHRINK
                | fcntl.F_SEAL_GROW
                | fcntl.F_SEAL_WRITE
            )
            if (
                not stat.S_ISREG(metadata.st_mode)
                or metadata.st_size != 32
                or seals & required != required
                or flags & fcntl.FD_CLOEXEC == 0
                or os.lseek(descriptor, 0, os.SEEK_CUR) != 0
                or "memfd:" not in os.readlink(f"/proc/self/fd/{descriptor}")
            ):
                raise KimiProviderBrokerError("broker returned an unsafe nonce descriptor")
        except BaseException:
            os.close(descriptor)
            raise
        # LinuxBubblewrapLauncher currently validates the concrete lease class
        # as well as its fields.  Import lazily so the standalone worker does
        # not import the launcher and a future integration can avoid a module
        # initialization cycle.
        from .isolated_launcher import BrokerNonceFD as LauncherBrokerNonceFD

        return LauncherBrokerNonceFD(fd=descriptor, lease_id=lease_id)

    def release_nonce(
        self,
        lease_id: str,
        *,
        run_id: str,
        stage_index: int,
        purpose: str,
    ) -> None:
        if run_id != self.run_id:
            raise KimiProviderBrokerError("cross-run nonce release rejected")
        self._rpc(
            {
                "operation": "release_nonce",
                "lease_id": lease_id,
                "run_id": run_id,
                "case_id": self.case_id,
                "trial_id": self.trial_id,
                "stage_index": stage_index,
                "purpose": purpose,
            }
        )

    @property
    def active_lease_count(self) -> int:
        response, _ = self._rpc(
            {
                "operation": "status",
                "run_id": self.run_id,
                "case_id": self.case_id,
                "trial_id": self.trial_id,
            }
        )
        count = response.get("active_lease_count")
        if not isinstance(count, int) or isinstance(count, bool) or count < 0:
            raise KimiProviderBrokerError("broker returned an invalid lease count")
        return count

    def configure_instruction_observer(
        self,
        *,
        run_id: str,
        stage_index: int,
        marker: bytes,
        expected_roles: Sequence[str] = ("system", "user", "user"),
    ) -> Path:
        """Arm a body-redacting observer before one stage starts.

        The marker is sent only over the private parent/worker control socket
        and retained in worker memory.  It is never written to the observer
        evidence file.
        """

        if run_id != self.run_id:
            raise KimiProviderBrokerError("cross-run observer configuration rejected")
        if (
            not isinstance(stage_index, int)
            or isinstance(stage_index, bool)
            or stage_index < 0
            or not isinstance(marker, bytes)
            or not 1 <= len(marker) <= _MAX_INSTRUCTION_MARKER
            or b"\0" in marker
        ):
            raise KimiProviderBrokerError("instruction observer marker is invalid")
        try:
            marker.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise KimiProviderBrokerError(
                "instruction observer marker must be UTF-8"
            ) from exc
        roles = tuple(expected_roles)
        if (
            not roles
            or len(roles) > 64
            or any(
                not isinstance(role, str)
                or _SAFE_ID_RE.fullmatch(role) is None
                for role in roles
            )
        ):
            raise KimiProviderBrokerError("instruction observer roles are invalid")
        if stage_index in self._instruction_observers:
            raise KimiProviderBrokerError(
                "instruction observer is already configured for this stage"
            )
        marker_sha256 = hashlib.sha256(marker).hexdigest()
        response, _ = self._rpc(
            {
                "operation": "configure_instruction_observer",
                "run_id": self.run_id,
                "case_id": self.case_id,
                "trial_id": self.trial_id,
                "stage_index": stage_index,
                "marker_base64": base64.b64encode(marker).decode("ascii"),
                "marker_sha256": marker_sha256,
                "expected_roles": list(roles),
            }
        )
        raw_path = response.get("path")
        if not isinstance(raw_path, str):
            raise KimiProviderBrokerError("broker omitted observer path")
        path = Path(raw_path).absolute()
        try:
            path.relative_to(self.root)
        except ValueError as exc:
            raise KimiProviderBrokerError("observer path escapes broker root") from exc
        expected_name = (
            f"request-observer-kimi-{self.run_id}-stage-{stage_index:03d}.jsonl"
        )
        if (
            path.name != expected_name
            or path.is_symlink()
            or not path.is_file()
            or stat.S_IMODE(path.stat().st_mode) != 0o600
            or path.read_bytes()
        ):
            raise KimiProviderBrokerError("broker observer file is not a private empty file")
        self._instruction_observers[stage_index] = (path, marker_sha256, roles)
        return path

    def finalize_instruction_observer(
        self, *, run_id: str, stage_index: int
    ) -> InstructionRequestObservation:
        """Freeze and validate direct evidence for one stage request."""

        if run_id != self.run_id:
            raise KimiProviderBrokerError("cross-run observer finalization rejected")
        configured = self._instruction_observers.get(stage_index)
        if configured is None:
            raise KimiProviderBrokerError(
                "instruction observer was not configured for this stage"
            )
        path, marker_sha256, expected_roles = configured
        response, _ = self._rpc(
            {
                "operation": "finalize_instruction_observer",
                "run_id": self.run_id,
                "case_id": self.case_id,
                "trial_id": self.trial_id,
                "stage_index": stage_index,
            }
        )
        if path.is_symlink() or not path.is_file() or stat.S_IMODE(path.stat().st_mode) != 0o600:
            raise KimiProviderBrokerError("instruction observer path drifted")
        raw = path.read_bytes()
        digest = hashlib.sha256(raw).hexdigest()
        lines = raw.splitlines()
        if (
            response.get("path") != str(path)
            or response.get("sha256") != digest
            or response.get("line_count") != len(lines)
        ):
            raise KimiProviderBrokerError("instruction observer snapshot drifted")
        matches: list[tuple[int, Mapping[str, Any]]] = []
        for line_number, line in enumerate(lines, 1):
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise KimiProviderBrokerError(
                    "instruction observer contains malformed JSON"
                ) from exc
            if not isinstance(record, Mapping) or (
                record.get("schema_name") != REQUEST_OBSERVATION_SCHEMA_NAME
                or record.get("schema_version") != REQUEST_OBSERVATION_SCHEMA_VERSION
                or record.get("harness_id") != "kimi"
                or record.get("run_id") != self.run_id
                or record.get("case_id") != self.case_id
                or record.get("trial_id") != self.trial_id
                or record.get("stage_index") != stage_index
                or record.get("sequence") != line_number
                or not isinstance(record.get("time"), str)
                or not isinstance(record.get("body_sha256"), str)
                or _SHA256_RE.fullmatch(str(record.get("body_sha256"))) is None
                or record.get("expected_substring_sha256") != marker_sha256
            ):
                raise KimiProviderBrokerError(
                    "instruction observer record identity/hash drifted"
                )
            if (
                record.get("expected_substring_present") is True
                and record.get("message_roles") == list(expected_roles)
            ):
                matches.append((line_number, record))
        if not matches:
            raise KimiProviderBrokerError(
                "no provider request directly contained the configured instruction marker"
            )
        line_number, record = matches[0]
        return InstructionRequestObservation(
            path=path,
            sha256=digest,
            line=line_number,
            line_count=len(lines),
            body_sha256=str(record["body_sha256"]),
            marker_sha256=marker_sha256,
            message_roles=expected_roles,
            observed_time=str(record["time"]),
        )

    def _stop_owned_process(self) -> None:
        process = self._process
        if process is None or process.poll() is not None:
            return
        try:
            if _process_start_time(process.pid) != getattr(self, "start_time", None):
                return
            process.terminate()
            process.wait(timeout=3)
        except (KimiProviderBrokerError, subprocess.TimeoutExpired):
            if process.poll() is None and _process_start_time(process.pid) == getattr(
                self, "start_time", None
            ):
                process.kill()
                process.wait(timeout=3)

    def close(self) -> None:
        if self._closed:
            return
        try:
            try:
                self._rpc(
                    {
                        "operation": "shutdown",
                        "run_id": self.run_id,
                        "case_id": self.case_id,
                        "trial_id": self.trial_id,
                    }
                )
            except (KimiProviderBrokerError, OSError):
                pass
            if self._process is not None:
                try:
                    self._process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    self._stop_owned_process()
        finally:
            self._closed = True
            self._control.close()
            if self._process is not None and self._process.stderr is not None:
                self._process.stderr.close()

    def __enter__(self) -> "RunScopedProviderBroker":
        return self

    def __exit__(self, *_: object) -> None:
        self.close()


class _Worker:
    def __init__(self, args: argparse.Namespace) -> None:
        self.run_id = _require_run_id(args.run_id)
        self.case_id = _require_id(args.case_id, "case_id")
        self.trial_id = _require_id(args.trial_id, "trial_id")
        self.root = Path(args.root).absolute()
        if (
            not self.root.is_dir()
            or self.root.is_symlink()
            or self.root.resolve(strict=True) != self.root
            or self.root.stat().st_uid != os.getuid()
            or stat.S_IMODE(self.root.stat().st_mode) != 0o700
            or "kimi" not in self.root.as_posix().casefold()
            or self.run_id not in self.root.as_posix()
            or self.root.name
            != broker_root_name(self.run_id, self.case_id, self.trial_id)
        ):
            raise KimiProviderBrokerError("worker root is not private Kimi ownership")
        for key in os.environ:
            if _SENSITIVE_ENV_RE.search(key):
                raise KimiProviderBrokerError(
                    "credential-like environment key reached provider broker"
                )
        self.endpoint = UpstreamEndpoint(
            scheme=args.upstream_scheme,
            host=args.upstream_host,
            port=args.upstream_port,
            path_prefix=args.upstream_path_prefix,
            tls_verified=args.upstream_scheme == "https",
        )
        # Re-validate the worker-side representation without consulting DNS.
        reconstructed = (
            f"{self.endpoint.scheme}://{self.endpoint.authority}"
            f"{self.endpoint.path_prefix}"
        )
        allowed = [self.endpoint.host] if self.endpoint.scheme == "https" else []
        if UpstreamEndpoint.parse(reconstructed, allowed_https_hosts=allowed) != self.endpoint:
            raise KimiProviderBrokerError("worker upstream identity drifted")
        if not 1.0 <= args.upstream_timeout <= 3600.0:
            raise KimiProviderBrokerError("upstream timeout is out of range")
        self.upstream_timeout = args.upstream_timeout
        self.control = socket.socket(fileno=args.control_fd)
        if self.control.family != socket.AF_UNIX or self.control.type & 0xF != socket.SOCK_SEQPACKET:
            raise KimiProviderBrokerError("worker control descriptor is not SOCK_SEQPACKET")
        self.control.settimeout(0.25)
        fcntl.fcntl(args.credential_fd, fcntl.F_SETFD, fcntl.FD_CLOEXEC)
        self.credential = self._read_credential(args.credential_fd)
        os.close(args.credential_fd)
        self.credential_transport = args.credential_transport
        self.socket_path = self.root / BROKER_SOCKET_BASENAME
        self.attestation_path = self.root / f"attestation-kimi-{self.run_id}.json"
        self.audit_attestation_path = (
            self.root / f"audit-attestation-kimi-{self.run_id}.json"
        )
        self.audit_log_path = self.root / f"audit-kimi-{self.run_id}.jsonl"
        for path in (
            self.socket_path,
            self.attestation_path,
            self.audit_attestation_path,
            self.audit_log_path,
        ):
            if path.exists() or path.is_symlink():
                raise KimiProviderBrokerError("worker output path already exists")
        self.server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM | socket.SOCK_CLOEXEC)
        self.server.bind(str(self.socket_path))
        os.chmod(self.socket_path, 0o600)
        self.server.listen(32)
        self.server.settimeout(0.25)
        self.stop = threading.Event()
        self.lock = threading.Lock()
        self.leases: dict[str, _Lease] = {}
        self.observer_lock = threading.Lock()
        self.instruction_observers: dict[int, _InstructionObserver] = {}
        self.sequence = 0
        self.connection_threads: set[threading.Thread] = set()
        self.data_thread = threading.Thread(target=self._serve_data, daemon=True)

    @staticmethod
    def _read_credential(descriptor: int) -> bytearray:
        value = bytearray()
        while len(value) <= 16 * 1024:
            chunk = os.read(descriptor, min(4096, 16 * 1024 + 1 - len(value)))
            if not chunk:
                break
            value.extend(chunk)
        if not value or len(value) > 16 * 1024 or any(byte in value for byte in b"\r\n\0"):
            _wipe(value)
            raise KimiProviderBrokerError("credential descriptor content is invalid")
        return value

    def _audit(self, event: str, **fields: Any) -> None:
        with self.lock:
            self.sequence += 1
            sequence = self.sequence
        document = {
            "schema_name": "safety_bench_kimi_provider_broker_event",
            "schema_version": 1,
            "harness_id": "kimi",
            "run_id": self.run_id,
            "case_id": self.case_id,
            "trial_id": self.trial_id,
            "pid": os.getpid(),
            "process_start_time": _process_start_time(os.getpid()),
            "sequence": sequence,
            "event": event,
            **fields,
        }
        payload = (
            json.dumps(document, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
            + "\n"
        ).encode("utf-8")
        flags = os.O_WRONLY | os.O_APPEND | os.O_CREAT
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        descriptor = os.open(self.audit_log_path, flags, 0o600)
        try:
            os.write(descriptor, payload)
            os.fsync(descriptor)
        finally:
            os.close(descriptor)

    def _write_attestations(self) -> None:
        pid = os.getpid()
        executable = Path(f"/proc/{pid}/exe").resolve(strict=True)
        implementation = Path(__file__).resolve(strict=True)
        metadata = self.socket_path.stat()
        # This exact field set is consumed by LinuxBubblewrapLauncher v1.  The
        # case/trial identity is also made explicit in the separate audit
        # attestation below; broker_kind keeps the launcher-facing file bound to
        # the same identity without changing the shared launcher contract.
        launcher_document: dict[str, Any] = {
            "schema_name": BROKER_ATTESTATION_SCHEMA_NAME,
            "schema_version": BROKER_ATTESTATION_SCHEMA_VERSION,
            "harness_id": "kimi",
            "run_id": self.run_id,
            "broker_kind": (
                "run-scoped-provider-broker-v1;"
                f"case_id={self.case_id};trial_id={self.trial_id}"
            ),
            "socket_path": str(self.socket_path),
            "socket_identity": {
                "device": metadata.st_dev,
                "inode": metadata.st_ino,
                "uid": metadata.st_uid,
                "gid": metadata.st_gid,
                "mode": stat.S_IMODE(metadata.st_mode),
            },
            "process": {
                "pid": pid,
                "start_time": _process_start_time(pid),
                "executable_path": str(executable),
                "executable_sha256": _file_sha256(executable),
                "cmdline_sha256": _process_cmdline_sha256(pid),
            },
            "implementation": {
                "path": str(implementation),
                "sha256": _file_sha256(implementation),
            },
            "credential_boundary": {
                "upstream_credential_transport": "inherited_fd",
                "credential_fd_cloexec": True,
                "external_credentials_in_environment": False,
                "external_credentials_in_filesystem": False,
                "external_credentials_persisted": False,
            },
            "nonce_boundary": {
                "issuance_transport": "sealed_memfd",
                "nonce_length_bytes": 32,
                "volatile_only": True,
                "unauthorized_nonce_rejected": True,
                "released_nonce_rejected": True,
            },
        }
        launcher_document["attestation_payload_sha256"] = _canonical_sha256(
            launcher_document
        )
        _atomic_json(self.attestation_path, launcher_document)
        audit_document: dict[str, Any] = {
            "schema_name": AUDIT_ATTESTATION_SCHEMA_NAME,
            "schema_version": AUDIT_ATTESTATION_SCHEMA_VERSION,
            "harness_id": "kimi",
            "run_id": self.run_id,
            "case_id": self.case_id,
            "trial_id": self.trial_id,
            "pid": pid,
            "process_start_time": _process_start_time(pid),
            "process_executable_path": str(executable),
            "process_executable_sha256": _file_sha256(executable),
            "process_cmdline_sha256": _process_cmdline_sha256(pid),
            "implementation_path": str(implementation),
            "implementation_sha256": _file_sha256(implementation),
            "socket_path": str(self.socket_path),
            "socket_device": metadata.st_dev,
            "socket_inode": metadata.st_ino,
            "socket_uid": metadata.st_uid,
            "socket_gid": metadata.st_gid,
            "socket_mode": stat.S_IMODE(metadata.st_mode),
            "root_mode": stat.S_IMODE(self.root.stat().st_mode),
            "credential_transport": self.credential_transport,
            "credential_location": "broker_memory_only_after_inherited_fd_read",
            "upstream": {
                "scheme": self.endpoint.scheme,
                "host": self.endpoint.host,
                "port": self.endpoint.port,
                "path_prefix": self.endpoint.path_prefix,
                "tls_certificate_verified": self.endpoint.tls_verified,
                "proxy_environment_used": False,
            },
            "nonce": {
                "transport": "sealed_memfd_over_private_control_socket",
                "length_bytes": 32,
                "successful_handshakes_per_nonce": 1,
                "replay_rejected": True,
            },
        }
        audit_document["attestation_payload_sha256"] = _canonical_sha256(
            audit_document
        )
        _atomic_json(self.audit_attestation_path, audit_document)

    def _issue(self, request: Mapping[str, Any]) -> tuple[Mapping[str, Any], int]:
        expected = {
            "operation",
            "run_id",
            "case_id",
            "trial_id",
            "stage_index",
            "purpose",
        }
        if set(request) != expected or (
            request.get("run_id") != self.run_id
            or request.get("case_id") != self.case_id
            or request.get("trial_id") != self.trial_id
            or not isinstance(request.get("stage_index"), int)
            or isinstance(request.get("stage_index"), bool)
            or int(request["stage_index"]) < -1
            or not isinstance(request.get("purpose"), str)
            or _SAFE_ID_RE.fullmatch(str(request["purpose"])) is None
        ):
            raise KimiProviderBrokerError("cross-identity nonce issue rejected")
        nonce = bytearray(secrets.token_bytes(32))
        lease_id = (
            f"nonce-kimi-{self.run_id}-"
            f"{secrets.token_hex(8)}"
        )
        lease = _Lease(
            run_id=self.run_id,
            stage_index=int(request["stage_index"]),
            purpose=str(request["purpose"]),
            nonce=nonce,
        )
        with self.lock:
            self.leases[lease_id] = lease
        descriptor = os.memfd_create(
            f"nonce-kimi-{self.run_id}", os.MFD_CLOEXEC | os.MFD_ALLOW_SEALING
        )
        try:
            os.write(descriptor, nonce)
            os.lseek(descriptor, 0, os.SEEK_SET)
            fcntl.fcntl(
                descriptor,
                fcntl.F_ADD_SEALS,
                fcntl.F_SEAL_SEAL
                | fcntl.F_SEAL_SHRINK
                | fcntl.F_SEAL_GROW
                | fcntl.F_SEAL_WRITE,
            )
        except BaseException:
            os.close(descriptor)
            with self.lock:
                removed = self.leases.pop(lease_id, None)
            if removed is not None:
                _wipe(removed.nonce)
            raise
        self._audit(
            "nonce_issued",
            lease_id=lease_id,
            stage_index=lease.stage_index,
            purpose=lease.purpose,
        )
        return {
            "ok": True,
            "operation": "issue_nonce",
            "lease_id": lease_id,
        }, descriptor

    def _release(self, request: Mapping[str, Any]) -> None:
        expected = {
            "operation",
            "lease_id",
            "run_id",
            "case_id",
            "trial_id",
            "stage_index",
            "purpose",
        }
        if set(request) != expected or (
            request.get("run_id") != self.run_id
            or request.get("case_id") != self.case_id
            or request.get("trial_id") != self.trial_id
        ):
            raise KimiProviderBrokerError("cross-identity nonce release rejected")
        lease_id = request.get("lease_id")
        if not isinstance(lease_id, str):
            raise KimiProviderBrokerError("nonce lease id is malformed")
        with self.lock:
            lease = self.leases.get(lease_id)
            if lease is None or (
                lease.run_id != request.get("run_id")
                or lease.stage_index != request.get("stage_index")
                or lease.purpose != request.get("purpose")
            ):
                raise KimiProviderBrokerError("nonce lease identity mismatch")
            self.leases.pop(lease_id)
        _wipe(lease.nonce)
        self._audit(
            "nonce_released",
            lease_id=lease_id,
            stage_index=lease.stage_index,
            purpose=lease.purpose,
            consumed=lease.consumed,
        )

    def _authorize(
        self, *, run_id: str, stage_index: int, purpose: str, nonce: bytes
    ) -> bool:
        with self.lock:
            for lease in self.leases.values():
                match = (
                    lease.run_id == run_id
                    and lease.stage_index == stage_index
                    and lease.purpose == purpose
                    and hmac.compare_digest(bytes(lease.nonce), nonce)
                )
                if match:
                    if lease.consumed:
                        return False
                    lease.consumed = True
                    return True
        return False

    def _configure_instruction_observer(
        self, request: Mapping[str, Any]
    ) -> Mapping[str, Any]:
        expected = {
            "operation",
            "run_id",
            "case_id",
            "trial_id",
            "stage_index",
            "marker_base64",
            "marker_sha256",
            "expected_roles",
        }
        if set(request) != expected or (
            request.get("run_id") != self.run_id
            or request.get("case_id") != self.case_id
            or request.get("trial_id") != self.trial_id
            or not isinstance(request.get("stage_index"), int)
            or isinstance(request.get("stage_index"), bool)
            or int(request["stage_index"]) < 0
            or not isinstance(request.get("marker_base64"), str)
            or not isinstance(request.get("marker_sha256"), str)
            or _SHA256_RE.fullmatch(str(request["marker_sha256"])) is None
            or not isinstance(request.get("expected_roles"), list)
            or not request["expected_roles"]
            or len(request["expected_roles"]) > 64
            or any(
                not isinstance(role, str) or _SAFE_ID_RE.fullmatch(role) is None
                for role in request["expected_roles"]
            )
        ):
            raise KimiProviderBrokerError(
                "instruction observer configuration identity is invalid"
            )
        try:
            marker = bytearray(
                base64.b64decode(str(request["marker_base64"]), validate=True)
            )
            marker.decode("utf-8")
        except (ValueError, UnicodeDecodeError) as exc:
            raise KimiProviderBrokerError(
                "instruction observer marker encoding is invalid"
            ) from exc
        if (
            not 1 <= len(marker) <= _MAX_INSTRUCTION_MARKER
            or b"\0" in marker
            or not hmac.compare_digest(
                hashlib.sha256(marker).hexdigest(), str(request["marker_sha256"])
            )
        ):
            _wipe(marker)
            raise KimiProviderBrokerError(
                "instruction observer marker digest is invalid"
            )
        stage_index = int(request["stage_index"])
        path = self.root / (
            f"request-observer-kimi-{self.run_id}-stage-{stage_index:03d}.jsonl"
        )
        with self.observer_lock:
            if stage_index in self.instruction_observers:
                _wipe(marker)
                raise KimiProviderBrokerError(
                    "instruction observer stage is already configured"
                )
            if path.exists() or path.is_symlink():
                _wipe(marker)
                raise KimiProviderBrokerError(
                    "instruction observer evidence path already exists"
                )
            flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
            if hasattr(os, "O_NOFOLLOW"):
                flags |= os.O_NOFOLLOW
            descriptor = os.open(path, flags, 0o600)
            os.close(descriptor)
            self.instruction_observers[stage_index] = _InstructionObserver(
                stage_index=stage_index,
                path=path,
                marker=marker,
                marker_sha256=str(request["marker_sha256"]),
                expected_roles=tuple(request["expected_roles"]),
            )
        self._audit(
            "instruction_observer_configured",
            stage_index=stage_index,
            marker_sha256=str(request["marker_sha256"]),
            expected_role_count=len(request["expected_roles"]),
        )
        return {
            "ok": True,
            "operation": "configure_instruction_observer",
            "path": str(path),
        }

    @staticmethod
    def _message_strings(value: Any) -> list[str]:
        strings: list[str] = []
        if isinstance(value, str):
            strings.append(value)
        elif isinstance(value, Mapping):
            for child in value.values():
                strings.extend(_Worker._message_strings(child))
        elif isinstance(value, list):
            for child in value:
                strings.extend(_Worker._message_strings(child))
        return strings

    def _observe_instruction_request(
        self, *, stage_index: int, target: str, body: bytes
    ) -> None:
        with self.observer_lock:
            observer = self.instruction_observers.get(stage_index)
            if observer is None:
                return
            if observer.finalized:
                raise KimiProviderBrokerError(
                    "provider request arrived after observer finalization"
                )
            roles: list[str] = []
            message_strings: list[str] = []
            try:
                document = json.loads(body.decode("utf-8"))
            except (UnicodeDecodeError, json.JSONDecodeError):
                document = None
            if isinstance(document, Mapping):
                messages = document.get("messages")
                if isinstance(messages, list):
                    for message in messages:
                        if not isinstance(message, Mapping):
                            roles = []
                            message_strings = []
                            break
                        role = message.get("role")
                        if not isinstance(role, str):
                            roles = []
                            message_strings = []
                            break
                        roles.append(role)
                        message_strings.extend(
                            self._message_strings(message.get("content"))
                        )
            marker_text = bytes(observer.marker).decode("utf-8")
            present = any(marker_text in value for value in message_strings)
            observer.sequence += 1
            record = {
                "schema_name": REQUEST_OBSERVATION_SCHEMA_NAME,
                "schema_version": REQUEST_OBSERVATION_SCHEMA_VERSION,
                "harness_id": "kimi",
                "run_id": self.run_id,
                "case_id": self.case_id,
                "trial_id": self.trial_id,
                "stage_index": stage_index,
                "sequence": observer.sequence,
                "time": datetime.now(timezone.utc).isoformat(),
                "body_sha256": hashlib.sha256(body).hexdigest(),
                "body_bytes": len(body),
                "target_sha256": hashlib.sha256(target.encode("utf-8")).hexdigest(),
                "message_roles": roles,
                "expected_substring_present": present,
                "expected_substring_sha256": observer.marker_sha256,
            }
            payload = (
                json.dumps(
                    record,
                    sort_keys=True,
                    separators=(",", ":"),
                    ensure_ascii=False,
                )
                + "\n"
            ).encode("utf-8")
            flags = os.O_WRONLY | os.O_APPEND
            if hasattr(os, "O_NOFOLLOW"):
                flags |= os.O_NOFOLLOW
            descriptor = os.open(observer.path, flags)
            try:
                view = memoryview(payload)
                while view:
                    written = os.write(descriptor, view)
                    if written <= 0:
                        raise KimiProviderBrokerError(
                            "instruction observer append failed"
                        )
                    view = view[written:]
                os.fsync(descriptor)
            finally:
                os.close(descriptor)

    def _finalize_instruction_observer(
        self, request: Mapping[str, Any]
    ) -> Mapping[str, Any]:
        expected = {
            "operation",
            "run_id",
            "case_id",
            "trial_id",
            "stage_index",
        }
        if set(request) != expected or (
            request.get("run_id") != self.run_id
            or request.get("case_id") != self.case_id
            or request.get("trial_id") != self.trial_id
            or not isinstance(request.get("stage_index"), int)
            or isinstance(request.get("stage_index"), bool)
            or int(request["stage_index"]) < 0
        ):
            raise KimiProviderBrokerError(
                "instruction observer finalization identity is invalid"
            )
        stage_index = int(request["stage_index"])
        with self.observer_lock:
            observer = self.instruction_observers.get(stage_index)
            if observer is None or observer.finalized:
                raise KimiProviderBrokerError(
                    "instruction observer cannot be finalized"
                )
            observer.finalized = True
            raw = observer.path.read_bytes()
            line_count = len(raw.splitlines())
            digest = hashlib.sha256(raw).hexdigest()
            _wipe(observer.marker)
        self._audit(
            "instruction_observer_finalized",
            stage_index=stage_index,
            line_count=line_count,
            evidence_sha256=digest,
        )
        return {
            "ok": True,
            "operation": "finalize_instruction_observer",
            "path": str(observer.path),
            "sha256": digest,
            "line_count": line_count,
        }

    @staticmethod
    def _read_line(reader: Any, label: str) -> bytes:
        line = reader.readline(_MAX_HTTP_LINE + 1)
        if len(line) > _MAX_HTTP_LINE or (line and not line.endswith(b"\n")):
            raise KimiProviderBrokerError(f"{label} is too large")
        return line

    def _upstream_target(self, target: str) -> str | None:
        if not target.startswith("/") or "\0" in target:
            return None
        parsed = urlsplit(target)
        if parsed.scheme or parsed.netloc or parsed.fragment:
            return None
        if ".." in parsed.path.split("/"):
            return None
        prefix = self.endpoint.path_prefix
        if parsed.path == _CLIENT_RELAY_PATH_PREFIX or parsed.path.startswith(
            _CLIENT_RELAY_PATH_PREFIX + "/"
        ):
            if prefix == "/":
                mapped = parsed.path
            else:
                mapped = prefix + parsed.path[len(_CLIENT_RELAY_PATH_PREFIX) :]
        elif prefix == "/" or parsed.path == prefix or parsed.path.startswith(
            prefix + "/"
        ):
            mapped = parsed.path
        else:
            return None
        if parsed.query:
            return f"{mapped}?{parsed.query}"
        return mapped

    def _target_allowed(self, target: str) -> bool:
        return self._upstream_target(target) is not None

    def _read_request(self, reader: Any) -> tuple[str, str, list[tuple[str, str]], bytes] | None:
        line = self._read_line(reader, "HTTP request line")
        if not line:
            return None
        try:
            method, target, version = line.rstrip(b"\r\n").decode("ascii").split(" ")
        except (UnicodeDecodeError, ValueError) as exc:
            raise KimiProviderBrokerError("HTTP request line is malformed") from exc
        if (
            method not in {"GET", "POST"}
            or version != "HTTP/1.1"
            or (upstream_target := self._upstream_target(target)) is None
        ):
            raise KimiProviderBrokerError("HTTP request target or method is not allowed")
        headers: list[tuple[str, str]] = []
        content_length: int | None = None
        for _ in range(_MAX_HTTP_HEADERS):
            raw = self._read_line(reader, "HTTP header")
            if raw in {b"\r\n", b"\n"}:
                break
            if not raw:
                raise KimiProviderBrokerError("HTTP headers ended unexpectedly")
            try:
                name, value = raw.decode("latin-1").rstrip("\r\n").split(":", 1)
            except ValueError as exc:
                raise KimiProviderBrokerError("HTTP header is malformed") from exc
            name = name.strip()
            value = value.strip()
            if not name or any(ord(char) < 33 or ord(char) > 126 for char in name):
                raise KimiProviderBrokerError("HTTP header name is malformed")
            lowered = name.casefold()
            if lowered == "transfer-encoding":
                raise KimiProviderBrokerError("chunked client requests are not accepted")
            if lowered == "content-length":
                if content_length is not None:
                    raise KimiProviderBrokerError("duplicate Content-Length rejected")
                try:
                    content_length = int(value)
                except ValueError as exc:
                    raise KimiProviderBrokerError("Content-Length is malformed") from exc
                continue
            if lowered not in _HOP_BY_HOP_HEADERS and lowered not in {
                "authorization",
                "host",
                "proxy-connection",
                "x-forwarded-for",
                "x-forwarded-host",
                "x-forwarded-proto",
            }:
                if "\r" in value or "\n" in value or "\0" in value:
                    raise KimiProviderBrokerError("HTTP header value is malformed")
                headers.append((name, value))
        else:
            raise KimiProviderBrokerError("too many HTTP headers")
        length = content_length or 0
        if length < 0 or length > _MAX_REQUEST_BODY:
            raise KimiProviderBrokerError("HTTP request body is too large")
        body = reader.read(length)
        if len(body) != length:
            raise KimiProviderBrokerError("HTTP request body ended unexpectedly")
        return method, upstream_target, headers, body

    def _upstream_connection(self) -> http.client.HTTPConnection:
        if self.endpoint.scheme == "https":
            context = ssl.create_default_context()
            context.check_hostname = True
            context.verify_mode = ssl.CERT_REQUIRED
            return http.client.HTTPSConnection(
                self.endpoint.host,
                self.endpoint.port,
                timeout=self.upstream_timeout,
                context=context,
            )
        return http.client.HTTPConnection(
            self.endpoint.host,
            self.endpoint.port,
            timeout=self.upstream_timeout,
        )

    def _forward(
        self,
        client: socket.socket,
        *,
        method: str,
        target: str,
        headers: list[tuple[str, str]],
        body: bytes,
    ) -> None:
        upstream = self._upstream_connection()
        status = 502
        response_bytes = 0
        authorization = b"Bearer " + bytes(self.credential)
        try:
            upstream.putrequest(method, target, skip_host=True, skip_accept_encoding=True)
            upstream.putheader("Host", self.endpoint.authority)
            for name, value in headers:
                upstream.putheader(name, value)
            upstream.putheader("Authorization", authorization)
            upstream.putheader("Content-Length", str(len(body)))
            upstream.putheader("Connection", "close")
            upstream.endheaders(body)
            response = upstream.getresponse()
            status = response.status
            reason = response.reason or ""
            client.sendall(f"HTTP/1.1 {status} {reason}\r\n".encode("latin-1"))
            for name, value in response.getheaders():
                if name.casefold() not in _HOP_BY_HOP_HEADERS | {"content-length"}:
                    client.sendall(f"{name}: {value}\r\n".encode("latin-1"))
            client.sendall(b"Transfer-Encoding: chunked\r\nConnection: keep-alive\r\n\r\n")
            while True:
                chunk = response.read(64 * 1024)
                if not chunk:
                    break
                response_bytes += len(chunk)
                client.sendall(f"{len(chunk):x}\r\n".encode("ascii") + chunk + b"\r\n")
            client.sendall(b"0\r\n\r\n")
        finally:
            upstream.close()
            del authorization
            self._audit(
                "request_forwarded",
                method=method,
                target_sha256=hashlib.sha256(target.encode("utf-8")).hexdigest(),
                request_body_bytes=len(body),
                response_status=status,
                response_body_bytes=response_bytes,
            )

    @staticmethod
    def _send_http_error(client: socket.socket, status: int, message: str) -> None:
        body = json.dumps({"error": message}, separators=(",", ":")).encode("utf-8")
        client.sendall(
            f"HTTP/1.1 {status} Broker Rejected\r\n".encode("ascii")
            + b"Content-Type: application/json\r\nConnection: close\r\n"
            + f"Content-Length: {len(body)}\r\n\r\n".encode("ascii")
            + body
        )

    def _handle_client(self, client: socket.socket) -> None:
        authorized = False
        requested_run = self.run_id
        stage_index = -1
        purpose = "invalid"
        with client:
            client.settimeout(15)
            buffer = bytearray()
            while b"\n" not in buffer and len(buffer) <= _MAX_HANDSHAKE_LINE:
                chunk = client.recv(4096)
                if not chunk:
                    return
                buffer.extend(chunk)
            line, separator, trailing = bytes(buffer).partition(b"\n")
            if not separator or trailing or len(line) > _MAX_HANDSHAKE_LINE:
                return
            try:
                request = json.loads(line.decode("utf-8"))
                if not isinstance(request, Mapping) or set(request) != {
                    "schema_name",
                    "schema_version",
                    "harness_id",
                    "run_id",
                    "stage_index",
                    "purpose",
                    "nonce",
                }:
                    return
                requested_run = str(request["run_id"])
                stage_index = int(request["stage_index"])
                purpose = str(request["purpose"])
                nonce = base64.b64decode(str(request["nonce"]), validate=True)
            except (ValueError, TypeError, UnicodeDecodeError, json.JSONDecodeError):
                return
            if len(nonce) != 32:
                return
            authorized = (
                request.get("schema_name") == HANDSHAKE_SCHEMA_NAME
                and request.get("schema_version") == 1
                and request.get("harness_id") == "kimi"
                and self._authorize(
                    run_id=requested_run,
                    stage_index=stage_index,
                    purpose=purpose,
                    nonce=nonce,
                )
            )
            response: dict[str, Any] = {
                "schema_name": HANDSHAKE_SCHEMA_NAME,
                "schema_version": 1,
                "ok": authorized,
                "run_id": requested_run,
                "stage_index": stage_index,
                "purpose": purpose,
                "proof": _ack_proof(
                    nonce,
                    run_id=requested_run,
                    stage_index=stage_index,
                    purpose=purpose,
                    ok=authorized,
                ),
            }
            if not authorized:
                response["reason"] = "unauthorized_nonce"
            client.sendall(
                json.dumps(response, sort_keys=True, separators=(",", ":")).encode(
                    "utf-8"
                )
                + b"\n"
            )
            self._audit(
                "handshake",
                requested_run_id=requested_run,
                stage_index=stage_index,
                purpose=purpose,
                authorized=authorized,
            )
            if not authorized or purpose != "model_relay":
                return
            client.settimeout(self.upstream_timeout)
            reader = client.makefile("rb")
            try:
                while not self.stop.is_set():
                    try:
                        parsed = self._read_request(reader)
                        if parsed is None:
                            return
                        method, target, headers, body = parsed
                        self._observe_instruction_request(
                            stage_index=stage_index,
                            target=target,
                            body=body,
                        )
                        self._forward(
                            client,
                            method=method,
                            target=target,
                            headers=headers,
                            body=body,
                        )
                    except KimiProviderBrokerError as exc:
                        self._audit(
                            "request_rejected",
                            reason=type(exc).__name__,
                        )
                        self._send_http_error(client, 400, "request rejected")
                        return
                    except (OSError, http.client.HTTPException, ssl.SSLError):
                        self._audit("upstream_error", reason="transport_error")
                        try:
                            self._send_http_error(client, 502, "upstream unavailable")
                        except OSError:
                            pass
                        return
            finally:
                reader.close()

    def _serve_data(self) -> None:
        while not self.stop.is_set():
            try:
                client, _ = self.server.accept()
            except socket.timeout:
                continue
            except OSError:
                return
            thread = threading.Thread(target=self._connection_entry, args=(client,), daemon=True)
            with self.lock:
                self.connection_threads.add(thread)
            thread.start()

    def _connection_entry(self, client: socket.socket) -> None:
        try:
            self._handle_client(client)
        finally:
            with self.lock:
                self.connection_threads.discard(threading.current_thread())

    def _control_loop(self) -> None:
        while not self.stop.is_set():
            try:
                request, descriptors = _recv_packet(self.control)
            except socket.timeout:
                continue
            except (OSError, KimiProviderBrokerError):
                self.stop.set()
                return
            for descriptor in descriptors:
                os.close(descriptor)
            operation = request.get("operation")
            try:
                if operation == "issue_nonce":
                    response, descriptor = self._issue(request)
                    try:
                        _send_packet(self.control, response, descriptor=descriptor)
                    finally:
                        os.close(descriptor)
                elif operation == "release_nonce":
                    self._release(request)
                    _send_packet(
                        self.control,
                        {"ok": True, "operation": "release_nonce"},
                    )
                elif operation == "configure_instruction_observer":
                    _send_packet(
                        self.control,
                        self._configure_instruction_observer(request),
                    )
                elif operation == "finalize_instruction_observer":
                    _send_packet(
                        self.control,
                        self._finalize_instruction_observer(request),
                    )
                elif operation == "status" and set(request) == {
                    "operation",
                    "run_id",
                    "case_id",
                    "trial_id",
                } and (
                    request.get("run_id"),
                    request.get("case_id"),
                    request.get("trial_id"),
                ) == (self.run_id, self.case_id, self.trial_id):
                    with self.lock:
                        count = len(self.leases)
                    _send_packet(
                        self.control,
                        {
                            "ok": True,
                            "operation": "status",
                            "active_lease_count": count,
                        },
                    )
                elif operation == "shutdown" and set(request) == {
                    "operation",
                    "run_id",
                    "case_id",
                    "trial_id",
                } and (
                    request.get("run_id"),
                    request.get("case_id"),
                    request.get("trial_id"),
                ) == (self.run_id, self.case_id, self.trial_id):
                    _send_packet(self.control, {"ok": True, "operation": "shutdown"})
                    self.stop.set()
                else:
                    raise KimiProviderBrokerError("control identity or operation rejected")
            except KimiProviderBrokerError as exc:
                _send_packet(
                    self.control,
                    {
                        "ok": False,
                        "operation": str(operation),
                        "reason": type(exc).__name__,
                    },
                )

    def run(self) -> int:
        self._write_attestations()
        self._audit(
            "started",
            credential_transport=self.credential_transport,
            upstream_scheme=self.endpoint.scheme,
            upstream_host=self.endpoint.host,
            upstream_port=self.endpoint.port,
        )
        self.data_thread.start()
        _send_packet(
            self.control,
            {"ok": True, "operation": "ready", "pid": os.getpid()},
        )
        try:
            self._control_loop()
        finally:
            self.stop.set()
            self.server.close()
            self.data_thread.join(timeout=2)
            with self.lock:
                threads = tuple(self.connection_threads)
                leases = tuple(self.leases.values())
                self.leases.clear()
            with self.observer_lock:
                observers = tuple(self.instruction_observers.values())
                self.instruction_observers.clear()
            for thread in threads:
                thread.join(timeout=2)
            for lease in leases:
                _wipe(lease.nonce)
            for observer in observers:
                _wipe(observer.marker)
            _wipe(self.credential)
            try:
                self.socket_path.unlink()
            except FileNotFoundError:
                pass
            self._audit("stopped", active_connections=len(threads))
            self.control.close()
        return 0


def _worker_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--worker", action="store_true", required=True)
    parser.add_argument("--control-fd", required=True, type=int)
    parser.add_argument("--credential-fd", required=True, type=int)
    parser.add_argument(
        "--credential-transport", required=True, choices=("pipe_fd", "sealed_memfd")
    )
    parser.add_argument("--root", required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--case-id", required=True)
    parser.add_argument("--trial-id", required=True)
    parser.add_argument("--upstream-scheme", required=True, choices=("http", "https"))
    parser.add_argument("--upstream-host", required=True)
    parser.add_argument("--upstream-port", required=True, type=int)
    parser.add_argument("--upstream-path-prefix", required=True)
    parser.add_argument("--upstream-timeout", required=True, type=float)
    return parser


def _worker_main(argv: Sequence[str]) -> int:
    args = _worker_parser().parse_args(argv)
    worker = _Worker(args)

    def stop_worker(_signal: int, _frame: object) -> None:
        worker.stop.set()

    signal.signal(signal.SIGTERM, stop_worker)
    signal.signal(signal.SIGINT, stop_worker)
    return worker.run()


def main(argv: Sequence[str] | None = None) -> int:
    arguments = list(sys.argv[1:] if argv is None else argv)
    if "--worker" not in arguments:
        raise SystemExit("provider_broker.py is an internal worker, not a user CLI")
    try:
        return _worker_main(arguments)
    except KimiProviderBrokerError as exc:
        # No values derived from the credential are included in error text.
        print(f"kimi-provider-broker: {exc}", file=sys.stderr)
        return 125


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "AUDIT_ATTESTATION_SCHEMA_NAME",
    "BROKER_ATTESTATION_SCHEMA_NAME",
    "BrokerNonceFD",
    "InstructionRequestObservation",
    "KimiProviderBrokerError",
    "REQUEST_OBSERVATION_SCHEMA_NAME",
    "REQUEST_OBSERVATION_SCHEMA_VERSION",
    "RunScopedProviderBroker",
    "UpstreamEndpoint",
]
